In [ ]:
%pip install numpy

In [3]:
import numpy as np


In [ ]:
l={1,2,3}
arr=np.array(l)

In [ ]:
arr

In [ ]:
a=np.zeros((2,3))

In [ ]:
np.ones_like(a)

In [ ]:
np.eye(4,4)

In [ ]:
np.eye(5,5,k=-1)


In [ ]:
np.full((3,3),4)

In [ ]:
np.empty((3,8))

In [ ]:
list(range(10))

In [ ]:
np.arange(4,18,2)

In [ ]:
np.linspace(0,10,20)

#creating nparr using random generator


In [ ]:
np.random.randint(0,20,size=(20,10))

In [ ]:
np.random.normal(loc=0.0,scale=1.0,size=10)#normal distribution

In [ ]:
np.random.uniform(0,100,10)#uniform distribution


In [73]:
a=np.arange(28)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [ ]:
a.reshape(5,2)

In [69]:
a.reshape(-1,5)#any row 5 columne

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
y=a.reshape(-1,2,2)# any 2:2 matrix
y

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]]])

In [79]:
y.shape

(7, 2, 2)

In [82]:
y>10

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]],

       [[False, False],
        [False,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [84]:
y.shape>(10,3)

False

In [94]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
a[[0,1,5]]#fancing indexing

array([0, 1, 5])

In [111]:
a%2==1

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [110]:
a[[True,False,False,False,False,True,False,False,False,False]]#boolean indexing

array([0, 5])

In [7]:
a=np.array([1,2,3]).reshape(1,3)
b=np.array([1,2,3]).reshape(3,1)



In [10]:
a.shape

(1, 3)

In [13]:
np.dot(a,b)

array([[14]])

In [16]:
a.sum()

6

In [26]:
b=np.ones((3,2))
b.sum(axis=0)#comume wise sum
b.sum(axis=1)# row wise


array([2., 2., 2.])

In [29]:
b.mean(axis=1)

array([1., 1., 1.])

In [40]:
a=b.flatten()#to one dim
a[1]=0
b

array([[0., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
a=b.ravel()#any change in a will change b also
a[2]=0
b

array([[0., 1.],
       [0., 1.],
       [1., 1.]])

In [52]:
a=np.ones((2,2))

np.linalg.inv(a)
np.linalg.det(a)

LinAlgError: Singular matrix

In [88]:
obs=np.array([111,118])
code=np.array([
    [102,203],
    [132,193],
    [45,155],
    [57,175]
])

In [98]:
obs_data=np.array([
    [111,118],
    [110,201]
])

In [90]:
(code-obs)

array([[ -9,  85],
       [ 21,  75],
       [-66,  37],
       [-54,  57]])

In [95]:
min(np.sqrt(np.square((code-obs)).sum(axis=1)))

75.66372975210778

In [97]:
np.sqrt(np.square((code-obs)).sum(axis=1)).argmin()

2

In [127]:
code=code.reshape(4,1,2)
code

array([[[102, 203]],

       [[132, 193]],

       [[ 45, 155]],

       [[ 57, 175]]])

In [125]:
np.shape(obs_data)

(2, 2)

In [126]:
np.shape(code)

(4, 1, 2)

In [115]:
code-obs_data

array([[[ -9,  85],
        [ -8,   2]],

       [[ 21,  75],
        [ 22,  -8]],

       [[-66,  37],
        [-65, -46]],

       [[-54,  57],
        [-53, -26]]])

In [123]:
np.sqrt(np.square((code-obs_data)).sum(axis=2))

array([[85.47514259,  8.24621125],
       [77.88452991, 23.40939982],
       [75.66372975, 79.63039621],
       [78.51751397, 59.03388857]])